#!/usr/bin/env node
/** Same-owner deterministic documentation projection. Never publishes to another repo. */
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { assertTaskProfileContract, type TaskProfileContract } from './governed-intake-task-profile.evaluate.ts';
import contract from './governed-intake-task-profile.v1.json' with { type: 'json' };

export function renderTaskProfileGuide(source: typeof contract, sourceDigest: string): string {
  assertTaskProfileContract(source as TaskProfileContract);
  const cell = (value: string): string => value.replaceAll('|', '\\|').replaceAll('\n', ' ');
  const lines = [
    '<!-- Generated by contracts/governed-intake-task-profile.generate.ts; do not hand-edit. -->',
    '# TaskProfileV1', '',
    `Source: [governed-intake-task-profile.v1.json](../contracts/governed-intake-task-profile.v1.json), schema \`${source.profileSchemaVersion}\`.`,
    `Source bytes: \`sha256:${sourceDigest}\`. This is a source digest, not a deployment receipt.`, '',
    source.purpose, '',
    'TaskProfileV1 is semantic task truth, not execution policy. It never records or infers a model,',
    'provider, account, pool, reasoning-effort setting, harness or benchmark. Design record and',
    'acceptance: [spencer-shadley/code#6458](https://github.com/spencer-shadley/code/issues/6458).', '',
    '## Placement in the triage lifecycle', '',
    `Produced after ${source.placement.after} and before ${source.placement.before}, applying to: ${source.placement.appliesTo.join(', ')}.`,
    source.placement.samePass, '',
    `Tracking parents: ${source.placement.trackingParents}`, '',
    '## The five categories', '',
    '| Category | Aliases | Question |', '|---|---|---|',
    ...source.categories.map((c: { id: string; aliases: string; question: string }) => `| \`${c.id}\` | ${cell(c.aliases)} | ${cell(c.question)} |`), '',
    '## Scoring', '',
    source.scoring.prompt, '',
    `Exactly ${source.scoring.totalPoints} integer points total, each category from ${source.scoring.minScore} to ${source.scoring.maxScore}.`, '',
    'Not meaning: ' + source.scoring.notMeaning.join(', ') + '.', '',
    '| Score | Anchor |', '|---|---|',
    ...Object.entries(source.scoring.anchors).map(([score, anchor]) => `| ${score} | ${cell(anchor as string)} |`), '',
    '## Confidence', '',
    '| Level | Definition |', '|---|---|',
    ...Object.entries(source.confidence.definitions).map(([level, definition]) => `| ${level} | ${cell(definition as string)} |`), '',
    'No `task-profile:high|medium|low` GitHub label exists in V1; confidence stays in the structured profile/receipt.', '',
    '## Label projection', '',
    `Apply a category label when its score is \u2265 ${source.labelProjection.threshold}; otherwise apply exactly \`${source.labelProjection.mixedLabel}\` and no category label.`,
    `At most ${source.labelProjection.maxCategoryLabels} category labels result from one valid vector, by construction of a ${source.scoring.totalPoints}-point budget.`,
    'Labels are a derived browsing/search projection, never the runtime routing input; runtime consumes the full structured vector.', '',
    '| Category | Label |', '|---|---|',
    ...Object.entries(source.labelProjection.categoryLabels).map(([id, label]) => `| \`${id}\` | \`${label}\` |`), '',
    '## Reuse and invalidation', '',
    'Reconsider triggers: ' + source.reuse.reconsiderTriggers.map((t: string) => `\`${t}\``).join(', ') + '.', '',
    'Never triggers reconsideration: ' + source.reuse.nonTriggers.map((t: string) => `\`${t}\``).join(', ') + '.', '',
    '## Legacy fallback', '',
    `Runtime fallback kind: \`${source.legacy.runtimeFallback}\`. ${source.legacy.rule}`, '',
    '## Calibration examples', '',
    '| ID | Scores | Labels |', '|---|---|---|',
    ...source.examples.map((example: { id: string; scores: Record<string, number>; labels: string[] }) =>
      `| ${example.id} | ${Object.entries(example.scores).filter(([, v]) => v > 0).map(([k, v]) => `${k} ${v}`).join(', ') || 'all 0'} | ${example.labels.map(l => `\`${l}\``).join(', ')} |`), '',
    'These are anchors, not keyword classifiers.', '',
    '## API integration and trust boundary', '',
    '- `bindTaskProfileContract` derives a deterministic canonical-JSON identity; a checklist/rubric revision bump is never required for a TaskProfile-only source change.',
    '- `validateTaskProfile` rejects any model/provider/account/pool/effort/harness/benchmark field; it accepts only the five-category vector, confidence and rationale.',
    '- `deriveTaskLabels` and `evaluateTaskLabelProjection` are pure projections; labels never replace the full vector as runtime input.',
    '- `decideTaskProfileReuse` reconsiders only on a listed trigger, a work-unit/scope-fingerprint mismatch or a contract-identity change; listed non-triggers (model release, benchmark movement, provider credits, harness/machine availability, comment churn, unrelated commits, profiler preference) never invalidate a valid record.',
    '- `resolveRuntimeTaskProfile` never fabricates a vector: missing, invalid, stale or contract-mismatched evidence resolves to `legacy-unprofiled`, never `human-required` and never a blocking state.',
    '- A tracking parent has no applicable aggregate profile; profile a distinct executable coordinator stage separately if one exists.', '',
    '## Verification', '', '```bash', 'npm run test:task-profile', 'npm run task-profile:check', '```', '',
  ];
  return lines.join('\n');
}

export function generate(check = false): void {
  const sourcePath = new URL('./governed-intake-task-profile.v1.json', import.meta.url);
  const outputPath = new URL('../docs/task-profile.md', import.meta.url);
  const bytes = readFileSync(sourcePath);
  const text = renderTaskProfileGuide(contract, createHash('sha256').update(bytes).digest('hex'));
  if (check) {
    if (readFileSync(outputPath, 'utf8') !== text) throw new Error('task_profile_documentation_drift');
  } else writeFileSync(outputPath, text, 'utf8');
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.some(arg => arg !== '--check')) throw new Error('usage: governed-intake-task-profile.generate.ts [--check]');
  generate(args.includes('--check'));
}
