#!/usr/bin/env node
/** Same-owner deterministic documentation projection. Never publishes to another repo. */
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { assertTriagePolicy, type TriagePolicy } from './governed-intake-triage-policy.evaluate.ts';
import policy from './governed-intake-triage-policy.v1.json' with { type: 'json' };

export function renderPolicyGuide(source: typeof policy, sourceDigest: string): string {
  assertTriagePolicy(source as TriagePolicy);
  const cell = (value: string): string => value.replaceAll('|', '\\|').replaceAll('\n', ' ');
  const lines = [
    '<!-- Generated by contracts/governed-intake-triage-policy.generate.ts; do not hand-edit. -->',
    '# Adopted triage policy', '',
    `Source: [governed-intake-triage-policy.v1.json](../contracts/governed-intake-triage-policy.v1.json), policy version ${source.version}, rubric version ${source.effortRubric.version}.`,
    `Source bytes: \`sha256:${sourceDigest}\`. This is a source digest, not a deployment receipt.`, '',
    '**Activation boundary:** this is a governed-intake source constituent. The live form and',
    'existing compatibility release are not advanced by this generator. Producer release integration',
    'and consumer validation remain required under [.github#13](https://github.com/spencer-shadley/.github/issues/13)',
    'and [code#6458](https://github.com/spencer-shadley/code/issues/6458). Do not claim live adoption from source tests.', '',
    '## Workflow', '', ...source.workflow.order.map((stage, index) => `${index + 1}. ${stage}`), '',
    'Child triage does not require a parent completion stamp. Implementation admission is separate from triage.', '',
    '## Resolved decomposition states', '',
    '| Disposition | Label projection | Effort | Tracking only | Qualified assessment | Independent confirmation |',
    '|---|---|---|---|---|---|',
    ...Object.entries(source.dispositions).map(([name, item]) => `| ${name} | ${item.labels.map(label => `\`${label}\``).join(' + ')} | ${item.efforts.join(', ')} | ${item.trackingOnly} | ${item.qualifiedAssessment} | ${item.independentConfirmation} |`), '',
    `Pending assessment is \`${source.pendingLabel}\`; missing labels do not make unresolved evidence disappear.`,
    `Retired progress labels: ${source.retiredProgressLabels.map(label => `\`${label}\``).join(', ')}.`,
    `Unsupported terminal synonyms: ${source.unsupportedTerminalAliases.map(label => `\`${label}\``).join(', ')}.`, '',
    '## Effort rubric', '', source.effortRubric.subject, '',
    '| Effort | Definition |', '|---|---|',
    ...Object.entries(source.effortRubric.definitions).map(([effort, definition]) => `| ${effort} | ${cell(definition)} |`), '',
    'Assess: ' + source.effortRubric.dimensions.join('; ') + '.', '',
    ...source.effortRubric.rules.map(rule => `- ${rule}`), '',
    '### Conditional examples', '',
    '| ID | Effort | Scope | Required assumptions |', '|---|---|---|---|',
    ...source.examples.map(example => `| ${example.id} | ${example.effort} | ${cell(example.scope)} | ${cell(example.assumptions.join('; '))} |`), '',
    'These examples guide qualified judgment; they are not keyword-based effort classifiers.', '',
    '### Compact sizing evidence', '', source.effortRubric.receiptFields.map(field => `\`${field}\``).join(', ') + '.', '',
    '## Capability and independent confirmation', '', source.capabilityPolicy.rule, '',
    `Selection policy owner: \`${source.capabilityPolicy.owner}\`; serving identity owner: \`${source.capabilityPolicy.servingIdentityOwner}\`.`,
    'This contract deliberately contains no model allowlist or provider-specific invocation logic.', '',
    source.evidence.independence + '.', '', source.capabilityPolicy.noEligibleCapacity, '', source.capabilityPolicy.mechanicalAssistance, '',
    '## Recovery without a progress label', '', source.concurrency.rule, '', source.concurrency.legacyCleanup, '', source.concurrency.staleWriters, '',
    '## Delta-only revalidation', '', source.migration.rule, '',
    'The pure planner distinguishes execution prerequisites from material result dependencies. An added scope check does not automatically rerun all downstream judgments. Re-plan after its result is observed; only actual changed inputs/results invalidate their consumers.', '',
    'Verified per-item receipts permit partial-run resume even when the prior whole-checklist completion is absent. Unverified checkboxes are not reusable evidence.', '',
    '## API integration and trust boundary', '',
    '- Bind the policy/rubric identities from the verified governed-intake release, never from issue text.',
    '- Compose `evaluateTriagePolicy` with the existing body/checklist/fingerprint evaluator; neither substitutes for the other.',
    '- Normalized trusted admissions come from verified Router and Gateway receipts. Checked prose, model names and caller-supplied eligibility booleans are not trusted admissions.',
    '- Graph validation remains owned by the Code shared decomposition core. This constituent validates its current receipt binding; it does not duplicate graph adjudication.',
    '- `implementationCandidate` and `evaluateImplementationCandidate` are selection predicates, not mutation authority, custody acquisition, dispatch or permission to spend.',
    '- The generic mutation authority remains responsible for bounded ownership, stale-writer fencing and serialized/idempotent child publication. These source tests do not prove those deployed paths.',
    '- `planRetiredProgressLabelCleanup` returns only cosmetic removals and must be applied through authorized transport. Failure to remove the label cannot invalidate semantic discovery.', '',
    '## Verification', '', '```bash', 'npm run test:triage-policy', 'npm run triage-policy:check', '```', '',
  ];
  return lines.join('\n');
}

export function generate(check = false): void {
  const sourcePath = new URL('./governed-intake-triage-policy.v1.json', import.meta.url);
  const outputPath = new URL('../docs/triage-policy.md', import.meta.url);
  const bytes = readFileSync(sourcePath);
  const text = renderPolicyGuide(policy, createHash('sha256').update(bytes).digest('hex'));
  if (check) {
    if (readFileSync(outputPath, 'utf8') !== text) throw new Error('triage_policy_documentation_drift');
  } else writeFileSync(outputPath, text, 'utf8');
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.some(arg => arg !== '--check')) throw new Error('usage: governed-intake-triage-policy.generate.ts [--check]');
  generate(args.includes('--check'));
}
